const Feedback = require('../models/Feedback');
const Grade = require('../models/Grade');

class FeedbackService {
  /**
   * Generate automated feedback based on submission and grade
   */
  static async generateAutoFeedback(submission, assignment, grade) {
    try {
      const detailedFeedback = [];
      const strengths = [];
      const areasForImprovement = [];
      const suggestions = [];

      // Analyze submission content
      if (submission.content) {
        const analysis = this._analyzeContent(submission.content);
        
        if (analysis.wordCount > 1000) {
          strengths.push('Comprehensive response with substantial content');
        } else {
          areasForImprovement.push('Response could be more detailed and comprehensive');
          suggestions.push('Add more examples and explanations to support your points');
        }

        if (analysis.hasStructure) {
          strengths.push('Well-organized content with clear structure');
        } else {
          areasForImprovement.push('Consider organizing your response with clear headings or sections');
          suggestions.push('Use bullet points or numbered lists to improve readability');
        }

        // Specific feedback based on grade
        if (grade.percentage >= 90) {
          detailedFeedback.push({
            section: 'Overall',
            comment: 'Excellent work! Your submission demonstrates strong understanding and clear communication.',
            severity: 'info'
          });
        } else if (grade.percentage >= 80) {
          detailedFeedback.push({
            section: 'Overall',
            comment: 'Good work. Your submission shows solid understanding with room for improvement.',
            severity: 'info'
          });
        } else if (grade.percentage >= 70) {
          detailedFeedback.push({
            section: 'Overall',
            comment: 'Acceptable work. Focus on the areas marked for improvement in the detailed feedback.',
            severity: 'warning'
          });
        } else {
          detailedFeedback.push({
            section: 'Overall',
            comment: 'This submission needs significant improvement. Please review the feedback carefully.',
            severity: 'critical'
          });
        }

        // Technical analysis
        if (analysis.hasCitations) {
          strengths.push('Good use of citations and references');
        } else if (submission.content.length > 500) {
          areasForImprovement.push('Add citations and references to support your claims');
          suggestions.push('Include at least 3-5 credible sources');
        }
      }

      // Generate learning resources
      const resources = this._generateResources(assignment, grade);

      // Create feedback document
      const feedback = new Feedback({
        submission: submission._id,
        student: submission.student,
        assignment: assignment._id,
        generalFeedback: `Your submission has been evaluated. Overall score: ${grade.percentage}%. See detailed feedback below.`,
        detailedFeedback,
        strengths,
        areasForImprovement,
        suggestions,
        resources,
        isAutoGenerated: true,
        generatedBy: 'automated'
      });

      return feedback;
    } catch (error) {
      console.error('Feedback generation error:', error);
      return null;
    }
  }

  /**
   * Analyze content for quality metrics
   */
  static _analyzeContent(content) {
    const words = content.split(/\s+/);
    const wordCount = words.length;
    
    // Check for structure (headings, bullet points, numbering)
    const hasStructure = /^[\s]*[-*+]|^[\s]*\d+\.|^#+/m.test(content);
    
    // Check for citations (URLs, citations, references)
    const hasCitations = /https?:\/\/|[\[\(][0-9]+[\]\)]|\[citation|References|Bibliography/i.test(content);

    return { wordCount, hasStructure, hasCitations };
  }

  /**
   * Generate resources based on assignment and grade
   */
  static _generateResources(assignment, grade) {
    const resources = [];

    // Always provide writing resources
    resources.push({
      title: 'Academic Writing Guide',
      url: 'https://owl.purdue.edu/owl/',
      description: 'Comprehensive guide for academic writing and citation styles'
    });

    // Add subject-specific resources based on course
    if (assignment.courseName) {
      resources.push({
        title: `${assignment.courseName} Resources`,
        url: '#',
        description: 'Course-specific learning materials and references'
      });
    }

    // Add remedial resources if grade is low
    if (grade.percentage < 70) {
      resources.push({
        title: 'Study Skills Tutorial',
        url: 'https://learningcenter.unc.edu/',
        description: 'Tips and strategies for improved academic performance'
      });
    }

    return resources;
  }

  /**
   * Create manual feedback from teacher
   */
  static async createManualFeedback(feedbackData) {
    const feedback = new Feedback({
      ...feedbackData,
      isAutoGenerated: false,
      generatedBy: 'teacher'
    });

    return feedback;
  }

  /**
   * Update existing feedback
   */
  static async updateFeedback(feedbackId, updateData) {
    const feedback = await Feedback.findByIdAndUpdate(
      feedbackId,
      updateData,
      { new: true }
    );

    return feedback;
  }

  /**
   * Mark feedback as viewed by student
   */
  static async markFeedbackViewed(feedbackId) {
    const feedback = await Feedback.findByIdAndUpdate(
      feedbackId,
      {
        studentViewed: true,
        studentViewedDate: new Date()
      },
      { new: true }
    );

    return feedback;
  }

  /**
   * Generate feedback for multiple submissions
   */
  static async generateBulkFeedback(assignmentId, submission, grades) {
    try {
      const feedbackPromises = [];

      for (const sub of submission) {
        const grade = grades.find(g => g.submission.toString() === sub._id.toString());
        if (grade) {
          feedbackPromises.push(
            this.generateAutoFeedback(sub, { courseName: 'Assignment' }, grade)
          );
        }
      }

      return await Promise.all(feedbackPromises);
    } catch (error) {
      console.error('Bulk feedback generation error:', error);
      return [];
    }
  }
}

module.exports = FeedbackService;
