const mongoose = require('mongoose');

const feedbackSchema = new mongoose.Schema({
  submission: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Submission',
    required: true
  },
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  assignment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Assignment',
    required: true
  },
  generalFeedback: String,
  detailedFeedback: [{
    section: String,
    comment: String,
    severity: {
      type: String,
      enum: ['info', 'warning', 'critical'],
      default: 'info'
    },
    lineNumber: Number
  }],
  strengths: [String],
  areasForImprovement: [String],
  suggestions: [String],
  resources: [{
    title: String,
    url: String,
    description: String
  }],
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  generatedBy: {
    type: String,
    enum: ['automated', 'teacher', 'peer', 'mixed'],
    default: 'automated'
  },
  teacher: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  },
  studentViewed: {
    type: Boolean,
    default: false
  },
  studentViewedDate: Date
}, { timestamps: true });

module.exports = mongoose.model('Feedback', feedbackSchema);
