const express = require('express');
const router = express.Router();
const { auth, checkRole } = require('../middleware/auth');
const Feedback = require('../models/Feedback');
const Submission = require('../models/Submission');
const Assignment = require('../models/Assignment');
const Grade = require('../models/Grade');
const FeedbackService = require('../services/FeedbackService');

/**
 * POST /api/feedback
 * Generate feedback for a submission
 */
router.post('/', auth, checkRole(['teacher', 'admin']), async (req, res) => {
  try {
    const { submissionId, assignmentId, isAutoGenerated, generalFeedback, detailedFeedback, strengths, areasForImprovement, suggestions } = req.body;

    // Validate input
    if (!submissionId || !assignmentId) {
      return res.status(400).json({
        success: false,
        message: 'Submission ID and Assignment ID are required'
      });
    }

    // Get submission, assignment, and grade
    const submission = await Submission.findById(submissionId);
    const assignment = await Assignment.findById(assignmentId);
    const grade = await Grade.findOne({ submission: submissionId });

    if (!submission || !assignment) {
      return res.status(404).json({
        success: false,
        message: 'Submission or Assignment not found'
      });
    }

    // Check if feedback already exists
    let feedback = await Feedback.findOne({ submission: submissionId });

    if (isAutoGenerated && !feedback && grade) {
      // Generate automated feedback
      feedback = await FeedbackService.generateAutoFeedback(submission, assignment, grade);
    } else if (!feedback) {
      // Create manual feedback
      feedback = new Feedback({
        submission: submissionId,
        student: submission.student,
        assignment: assignmentId,
        generalFeedback,
        detailedFeedback,
        strengths,
        areasForImprovement,
        suggestions,
        isAutoGenerated: false,
        generatedBy: 'teacher',
        teacher: req.user.id
      });
    } else {
      // Update existing feedback
      feedback = await FeedbackService.updateFeedback(feedback._id, {
        generalFeedback: generalFeedback || feedback.generalFeedback,
        detailedFeedback: detailedFeedback || feedback.detailedFeedback,
        strengths: strengths || feedback.strengths,
        areasForImprovement: areasForImprovement || feedback.areasForImprovement,
        suggestions: suggestions || feedback.suggestions,
        teacher: req.user.id
      });
    }

    if (!feedback) {
      return res.status(500).json({
        success: false,
        message: 'Error generating feedback'
      });
    }

    await feedback.save();

    // Update submission with feedback reference
    submission.feedback = feedback._id;
    submission.status = 'reviewed';
    await submission.save();

    res.status(201).json({
      success: true,
      message: 'Feedback created successfully',
      feedback: {
        id: feedback._id,
        submission: feedback.submission,
        student: feedback.student,
        isAutoGenerated: feedback.isAutoGenerated,
        generatedBy: feedback.generatedBy,
        strengths: feedback.strengths,
        areasForImprovement: feedback.areasForImprovement
      }
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: 'Error creating feedback'
    });
  }
});

/**
 * POST /api/feedback/auto/:assignmentId
 * Auto-generate feedback for all submissions
 */
router.post('/auto/:assignmentId', auth, checkRole(['teacher', 'admin']), async (req, res) => {
  try {
    const assignmentId = req.params.assignmentId;
    const submissions = await Submission.find({ assignment: assignmentId });
    const grades = await Grade.find({ assignment: assignmentId });
    const assignment = await Assignment.findById(assignmentId);

    if (!assignment) {
      return res.status(404).json({
        success: false,
        message: 'Assignment not found'
      });
    }

    const feedbacks = [];
    for (const submission of submissions) {
      const grade = grades.find(g => g.submission.toString() === submission._id.toString());
      if (grade) {
        const feedback = await FeedbackService.generateAutoFeedback(submission, assignment, grade);
        if (feedback) {
          await feedback.save();
          feedbacks.push(feedback);
          submission.feedback = feedback._id;
          await submission.save();
        }
      }
    }

    res.status(200).json({
      success: true,
      message: `Generated feedback for ${feedbacks.length} submissions`,
      feedbackCount: feedbacks.length
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: 'Error auto-generating feedback'
    });
  }
});

/**
 * GET /api/feedback/:id
 * Get feedback for a submission
 */
router.get('/:id', auth, async (req, res) => {
  try {
    const feedback = await Feedback.findById(req.params.id)
      .populate('student', 'firstName lastName email')
      .populate('submission')
      .populate('assignment', 'title courseCode');

    if (!feedback) {
      return res.status(404).json({
        success: false,
        message: 'Feedback not found'
      });
    }

    // Check authorization
    if (req.user.role === 'student' && feedback.student._id.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Access denied'
      });
    }

    // Mark as viewed if student is accessing
    if (req.user.role === 'student') {
      await FeedbackService.markFeedbackViewed(req.params.id);
    }

    res.status(200).json({
      success: true,
      feedback
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: 'Error fetching feedback'
    });
  }
});

/**
 * GET /api/feedback/submission/:submissionId
 * Get feedback for a specific submission
 */
router.get('/submission/:submissionId', auth, async (req, res) => {
  try {
    const feedback = await Feedback.findOne({ submission: req.params.submissionId })
      .populate('student', 'firstName lastName email')
      .populate('assignment', 'title courseCode');

    if (!feedback) {
      return res.status(404).json({
        success: false,
        message: 'Feedback not found'
      });
    }

    res.status(200).json({
      success: true,
      feedback
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: 'Error fetching feedback'
    });
  }
});

/**
 * PATCH /api/feedback/:id
 * Update feedback
 */
router.patch('/:id', auth, checkRole(['teacher', 'admin']), async (req, res) => {
  try {
    const feedback = await FeedbackService.updateFeedback(req.params.id, req.body);

    if (!feedback) {
      return res.status(404).json({
        success: false,
        message: 'Feedback not found'
      });
    }

    res.status(200).json({
      success: true,
      message: 'Feedback updated successfully',
      feedback
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: 'Error updating feedback'
    });
  }
});

module.exports = router;
